# This is a basic workflow to help you get started with Actions
name: progComp

# Definition des Triggers
on:
  push:
    paths:
    - 'division.cs'

jobs:
  build:
    # Festlegung des Betriebssystems
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: setup dotnet 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Compile file
      run: csc division.cs
